### ISSUE TITLE
authorized_userid() method in AbstractAuthorizationPolicy required?

### ISSUE THREAD

**Issue by shicky** [aio-libs/aiohttp_security#3]
I was wondering if authorized_userid() method in AbstractAuthorizationPolicy is necessary.
It seems like it duplicates functionality of identity() in AbstractIdentityPolicy.

```python
@asyncio.coroutine
@abc.abstractmethod
def authorized_userid(self, identity):
    """Retrieve authorized user id.
    Return the user_id of the user identified by the identity
    or 'None' if no user exists related to the identity.
    """
    pass
```
In demo code, it is used to get identities from database that are not disabled.
```python
@asyncio.coroutine
def authorized_user_id(self, identity):
    with (yield from self.dbengine) as conn:
        where = [db.users.c.login == identity, not db.users.c.disabled]
        query = db.users.count().where(sa.and_(*where))
        ret = yield from conn.scalar(query)
        if ret:
            return identity
        else:
            return None
```
I believe this check can be done in identify() method in AbstractIdentityPolicy instead.

**Comment by asvetlov** [comment]
Yes, it's required.
Just for note: userid is a persistent value but identity may be changed between user sessions.
