### ISSUE TITLE
Yum broken when RPM from this requirement with underscores.

### ISSUE THREAD

**Issue by mosquito** [aio-libs/aiohttp_security#6]
Please never use underscores in python-packages names.

[PEP-008 conatins](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)
> Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

We have a really problem. When our build system convert all dependencies to RPM (using [FPM](https://github.com/jordansissel/fpm)) yum is broken. We are can't use this package in our projects.

**Comment by asvetlov** [comment]
Fixed by 0.1.1 release

**Comment by mosquito** [comment]
Thank you. I hope that everything else packages will be without the underscore character soon.
